---
title: "A Grapher for Meritocracy-alike First Trial"
author: "Yon Kwon"
date: "13/08/2023"
output: html_document
---

# Grapher for Tzogos Sequel

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE) 
library(R.matlab)
library(ggplot2) # Plot
library(patchwork) # Plot patchwork
library(tidyr) # gather()
library(ggrepel) # geom_text_repel
library(viridis)
library(ggsci) # colormap
```

## Data Import & User Config
```{r data_file, eval=FALSE, include=FALSE}{r clear}
# rm(list=ls()) # Cleaning R environment
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) # Set SRC DIR as WD
file <- file.choose()
gc()
data <- readMat(file)
fig_id <- paste0(
  basename(file),
  'i', data$para.iteration,
  'm', data$para.g.m,
  'g', data$para.g
)

dms_label <- c(
  'Autonomous',
  'Rotating\nDictatorship',
  'Plurality\nVoting',
  'Two-stage\nVoting',
  'Belief\nAveraging'
)
dms_label <- ordered(dms_label, levels=dms_label)
```

## Figure 1 - Compare DMSs in a particular time period
```{r fig1}
set_fig1_dms <- c(1, 2, 3, 4, 5)
set_fig1_t <- data$para.time
set_fig1_t <- 1
dms_shape <- c(1,5,10,9)

set_fig1_y_label <- 'Average Competence'
set_fig1_outcome_bm <- data$r.abm.avg[set_fig1_dms, set_fig1_t]
set_fig1_outcome_bm_std <- data$r.abm.std[set_fig1_dms, set_fig1_t]
set_fig1_outcome_bm_label <- 'Best Matching'
set_fig1_outcome_rc <- data$r.arc.avg[set_fig1_dms, set_fig1_t]
set_fig1_outcome_rc_std <- data$r.arc.std[set_fig1_dms, set_fig1_t]
set_fig1_outcome_rc_label <- 'Rank Correlation'
set_fig1_outcome_bc <- data$r.abc.avg[set_fig1_dms, set_fig1_t]
set_fig1_outcome_bc_std <- data$r.abc.std[set_fig1_dms, set_fig1_t]
set_fig1_outcome_bc_label <- 'Belief Correlation'

# set_fig1_y_label <- 'Meritocracy Score'
# set_fig1_outcome_bm <- data$r.mbm.avg[set_fig1_dms, set_fig1_t]
# set_fig1_outcome_bm_std <- data$r.mbm.std[set_fig1_dms, set_fig1_t]
# set_fig1_outcome_bm_label <- 'Best Matching'
# set_fig1_outcome_rc <- data$r.mrc.avg[set_fig1_dms, set_fig1_t]
# set_fig1_outcome_rc_std <- data$r.mrc.std[set_fig1_dms, set_fig1_t]
# set_fig1_outcome_rc_label <- 'Rank Correlation'
# set_fig1_outcome_bc <- data$r.mbc.avg[set_fig1_dms, set_fig1_t]
# set_fig1_outcome_bc_std <- data$r.mbc.std[set_fig1_dms, set_fig1_t]
# set_fig1_outcome_bc_label <- 'Belief Correlation'

set_fig1_outcome_label <- c(set_fig1_outcome_bm_label, set_fig1_outcome_rc_label, set_fig1_outcome_bc_label)
set_fig1_outcome_label <- factor(set_fig1_outcome_label, levels = set_fig1_outcome_label)

label_size <- 8
tick_label_size <- 8

df_fig1 <- data.frame()
for( dms in 1:length(set_fig1_dms) ){
  df_next <- data.frame(
    dms = dms_label[set_fig1_dms[dms]],
    outcome_label = set_fig1_outcome_label[1],
    outcome_value = set_fig1_outcome_bm[dms],
    outcome_value_round = ifelse(set_fig1_outcome_bm[dms]>3, round(set_fig1_outcome_bm[dms]), ''),
    ci_min = set_fig1_outcome_bm[dms] - set_fig1_outcome_bm_std[dms] / sqrt(data$para.iteration),
    ci_max = set_fig1_outcome_bm[dms] + set_fig1_outcome_bm_std[dms] / sqrt(data$para.iteration)
  )
  df_fig1 <- rbind(df_fig1, df_next)
  
  df_next <- data.frame(
    dms = dms_label[set_fig1_dms[dms]],
    outcome_label = set_fig1_outcome_label[2],
    outcome_value = set_fig1_outcome_rc[dms],
    outcome_value_round = ifelse(set_fig1_outcome_rc[dms]>3, round(set_fig1_outcome_rc[dms]), ''),
    ci_min = set_fig1_outcome_rc[dms] - set_fig1_outcome_rc_std[dms] / sqrt(data$para.iteration),
    ci_max = set_fig1_outcome_rc[dms] + set_fig1_outcome_rc_std[dms] / sqrt(data$para.iteration)
  )
  df_fig1 <- rbind(df_fig1, df_next)
  
  df_next <- data.frame(
    dms = dms_label[set_fig1_dms[dms]],
    outcome_label = set_fig1_outcome_label[3],
    outcome_value = set_fig1_outcome_bc[dms],
    outcome_value_round = ifelse(set_fig1_outcome_rc[dms]>3, round(set_fig1_outcome_rc[dms]), ''),
    ci_min = set_fig1_outcome_bc[dms] - set_fig1_outcome_bc_std[dms] / sqrt(data$para.iteration),
    ci_max = set_fig1_outcome_bc[dms] + set_fig1_outcome_bc_std[dms] / sqrt(data$para.iteration)
  )
  df_fig1 <- rbind(df_fig1, df_next)
}

axes <- aes(
  x = dms, 
  y = outcome_value,
  ymin = ci_min,
  ymax = ci_max,
  group = outcome_label,
  color = outcome_label,
  fill = outcome_label,
  label = outcome_value_round
)

fig1 <- ggplot(data = df_fig1, mapping = axes) +
  geom_bar(stat = 'identity', position = 'dodge', color = 'black') +
  geom_errorbar(position = position_dodge(.9), width = .25, color='black') +
  geom_text_repel(position = position_dodge(.9), vjust = -.8, size=2, colour='black') +
  scale_color_npg() +
  scale_fill_npg() +
  scale_x_discrete('', labels=dms_label) +
  scale_y_continuous(expand = c(0,0))+
  ylab(set_fig1_y_label) +
  theme_classic()+
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    axis.text.x = element_text(color = 'black', angle=0),
    legend.title = element_blank(),
    legend.box="vertical",
    legend.position = 'right'
  )

fig1

fig1_params_label <- paste0(
  'fig1', 
  'dms', paste0(set_fig1_dms, collapse = ","),
  't', set_fig1_t
)

ggsave(
  paste0(fig_id, '_', fig1_params_label, '.png'),
  plot = fig1,
  units = 'in', 
  width = 6,
  height = 3,
  dpi = fig_dpi
)
```

## Figure 1 - Compare DMSs in a particular over time; Fixed competence assumption
```{r fig2}
set_fig2_dms <- c(1, 2, 3, 4, 5)
set_fig2_t <- data$para.time
dms_shape <- c(1,5,10,9)

set_fig2_y_label <- 'Average Competence'
set_fig2_outcome_bm <- data$r.abm.avg[set_fig2_dms, set_fig2_t]
set_fig2_outcome_bm_std <- data$r.abm.std[set_fig2_dms, set_fig2_t]
set_fig2_outcome_bm_label <- 'Best Matching'
set_fig2_outcome_rc <- data$r.arc.avg[set_fig2_dms, set_fig2_t]
set_fig2_outcome_rc_std <- data$r.arc.std[set_fig2_dms, set_fig2_t]
set_fig2_outcome_rc_label <- 'Rank Correlation'
set_fig2_outcome_bc <- data$r.abc.avg[set_fig2_dms, set_fig2_t]
set_fig2_outcome_bc_std <- data$r.abc.std[set_fig2_dms, set_fig2_t]
set_fig2_outcome_bc_label <- 'Belief Correlation'

set_fig2_outcome_label <- c(set_fig2_outcome_bm_label, set_fig2_outcome_rc_label, set_fig2_outcome_bc_label)
set_fig2_outcome_label <- factor(set_fig2_outcome_label, levels = set_fig2_outcome_label)

df_fig2 <- data.frame()
for( dms in 1:length(set_fig2_dms) ){
  df_next <- data.frame(
    dms = dms_label[set_fig2_dms[dms]],
    outcome_label = set_fig2_outcome_label[1],
    outcome_value = set_fig2_outcome_bm[dms],
    outcome_value_round = ifelse(set_fig2_outcome_bm[dms]>3, round(set_fig2_outcome_bm[dms]), ''),
    ci_min = set_fig2_outcome_bm[dms] - set_fig2_outcome_bm_std[dms] / sqrt(data$para.iteration),
    ci_max = set_fig2_outcome_bm[dms] + set_fig2_outcome_bm_std[dms] / sqrt(data$para.iteration)
  )
  df_fig2 <- rbind(df_fig2, df_next)
  
  df_next <- data.frame(
    dms = dms_label[set_fig2_dms[dms]],
    outcome_label = set_fig2_outcome_label[2],
    outcome_value = set_fig2_outcome_rc[dms],
    outcome_value_round = ifelse(set_fig2_outcome_rc[dms]>3, round(set_fig2_outcome_rc[dms]), ''),
    ci_min = set_fig2_outcome_rc[dms] - set_fig2_outcome_rc_std[dms] / sqrt(data$para.iteration),
    ci_max = set_fig2_outcome_rc[dms] + set_fig2_outcome_rc_std[dms] / sqrt(data$para.iteration)
  )
  df_fig2 <- rbind(df_fig2, df_next)
  
  df_next <- data.frame(
    dms = dms_label[set_fig2_dms[dms]],
    outcome_label = set_fig2_outcome_label[3],
    outcome_value = set_fig2_outcome_bc[dms],
    outcome_value_round = ifelse(set_fig2_outcome_rc[dms]>3, round(set_fig2_outcome_rc[dms]), ''),
    ci_min = set_fig2_outcome_bc[dms] - set_fig2_outcome_bc_std[dms] / sqrt(data$para.iteration),
    ci_max = set_fig2_outcome_bc[dms] + set_fig2_outcome_bc_std[dms] / sqrt(data$para.iteration)
  )
  df_fig2 <- rbind(df_fig2, df_next)
}

axes <- aes(
  x = dms, 
  y = outcome_value,
  ymin = ci_min,
  ymax = ci_max,
  group = outcome_label,
  color = outcome_label,
  fill = outcome_label,
  label = outcome_value_round
)

fig2 <- ggplot(data = df_fig2, mapping = axes) +
  geom_bar(stat = 'identity', position = 'dodge') +
  geom_errorbar(position = position_dodge(.9), width = .25) +
  geom_text_repel(position = position_dodge(.9), vjust = -.8, size=2, colour='black') +
  scale_color_npg() +
  scale_fill_npg() +
  scale_x_discrete('', labels=dms_label) +
  ylab(set_fig2_y_label) +
  theme_bw() +
  theme(
    text=element_text(size=label_size, color='black'),
    axis.title=element_text(size=label_size, color='black'),
    axis.text=element_text(size=tick_label_size, color='black'),
    axis.text.x = element_text(color = 'black', angle=0),
    legend.title = element_blank(),
    legend.box="vertical",
    legend.position = 'right'
  )

fig2

fig2_params_label <- paste0(
  'fig2', 
  'dms', paste0(set_fig2_dms, collapse = ","),
  't', set_fig2_t
)

ggsave(
  paste0(fig_id, '_', fig2_params_label, '.png'),
  plot = fig2,
  units = 'in', 
  width = 6,
  height = 3,
  dpi = fig_dpi
)
```

